#spring:
#  profiles:
#    active: usage_message

logging:
  level:
    org: ERROR

tutorial:
  client:
    duration: 10000
spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest